services:
  # 1. Python ML Service (FastAPI)
  - type: web
    name: cam-ml-engine
    env: docker
    dockerfilePath: ./ml-service/Dockerfile
    rootDir: .
    region: ohio
    plan: free

  # 2. Java Backend & Frontend (Spring Boot serving Static Files)
  - type: web
    name: cam-java-backend
    env: docker
    dockerfilePath: ./Dockerfile
    rootDir: .
    region: ohio
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: ML_SERVICE_URL
        fromService:
          name: cam-ml-engine
          type: web
          property: url
      - key: JWT_SECRET
        value: kBrEkn/5ZoZJtAAxT5MLMtNcLz7yr+gsbTrWxmEezko3hRf2zuwkpTq1wvPeXkTu
