spring.application.name=CreditAppraisalMemo

spring.datasource.url=jdbc:h2:mem:creditdb;
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8090

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=testingxyz123456@gmail.com
spring.mail.password=frke lppr oixr ncwq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.otp.expiry-minutes=5

spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always

app.documents.upload-dir=./uploads
app.cam.output-dir=./cam-reports
