spring.application.name=CreditAppraisalMemo

# Database Configuration
# PostgreSQL Config for Render
spring.datasource.url=jdbc:postgresql://dpg-d6o4f74r85hc73din2ug-a:5432/mydb_s5ix
spring.datasource.username=mydb_s5ix_user
spring.datasource.password=MBHplYgq4FbJp3tSzusw5fG8AEKxqrQD
spring.datasource.driver-class-name=org.postgresql.Driver

spring.h2.console.enabled=false

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8090

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=testingxyz123456@gmail.com
spring.mail.password=frke lppr oixr ncwq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.otp.expiry-minutes=5

# JWT signing secret — must be a Base64-encoded string of at least 32 bytes.
jwt.secret=kBrEkn/5ZoZJtAAxT5MLMtNcLz7yr+gsbTrWxmEezko3hRf2zuwkpTq1wvPeXkTu

spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always

app.documents.upload-dir=./uploads
app.cam.output-dir=./cam-reports

# Increase Max Upload Size
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
